### ISSUE TITLE
Feature: add an 'is this your first larp?' checkbox

### ISSUE THREAD

**Issue by ReneB** [evolution-events/Artaxerxes#114] opened 2020-07-08 15:36 UTC
In order to be (more) welcoming to first-time players and better understand their needs, we should be informed that someone has never larped before. We can't expect people to tell us if we don't ask, so let's ask.

**Comment by matthijskooijman** [comment] 2021-08-28 18:21
This is a duplicate of #28, so I'm closing this.

**Closed by matthijskooijman** 2021-08-28 18:21 UTC
